### ISSUE TITLE
EPG update error: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6'

### ISSUE THREAD

**Issue by rapi3** [cralin/plugin.video.TVOnline.ro#11]
De cateva zile nu mai poate sa updateze EPG-ul... 

log kodi:
```
2022-01-11 11:37:23.280 T:2459411312   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xf6' in position 35: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/service.py", line 313, in <module>
                                                schedule_jobs()
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/service.py", line 129, in schedule_jobs
                                                PVRIPTVSimpleClientIntegration_init_EPG_file()
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/service.py", line 257, in PVRIPTVSimpleClientIntegration_init_EPG_file
                                                PVRIPTVSimpleClientIntegration_update_EPG_file()
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/service.py", line 287, in PVRIPTVSimpleClientIntegration_update_EPG_file
                                                functions.digionline__updateEPGfile(_tmp_epg_file_, vars.__ServiceID__, vars.__ServiceSession__, MyServiceAddon_DataDir)
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/resources/lib/common/functions.py", line 1090, in digionline__updateEPGfile
                                                _data_file_.write(_line_ + "\n")
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 35: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by cralin** [comment]
Ai deschis issue pentru plugin.video.TVOnline in care raportezi o eroare generata de plugin.video.DigiOnline.ro

Pentru plugin.video.DigiOnline.ro nu mai fac bugfix-uri si nici nu mai adaug functionalitati noi.

Te rog sa verifici daca ai acelasi mesaj de eorare cu plugin.video.TVOnline.ro.

Multumesc.
