### ISSUE TITLE
KeyError: 'data' (arm, raspberry pi 4)

### ISSUE THREAD

**Issue by dimovnike** [cralin/plugin.video.TVOnline.ro#18]
Imi afiseaza canalele dar cand incerc sa intru pe unu din ele (de ex PRO TV) imi da eroare:

```
2022-10-20 17:22:36.050 T:2612     INFO <general>: CAddonMgr::FindAddon: plugin.video.TVOnline.ro v19.2.9 installed
2022-10-20 17:22:36.053 T:2634     INFO <general>: initializing python engine.
2022-10-20 17:22:36.303 T:2312  WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2022-10-20 17:22:44.421 T:2312    ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2022-10-20 17:22:45.528 T:2642     INFO <general>: initializing python engine.
2022-10-20 17:22:47.785 T:2642     INFO <general>: CPythonInvoker(23, /home/pi/.kodi/addons/plugin.video.TVOnline.ro/main.py): script successfully run
2022-10-20 17:22:47.940 T:2642     INFO <general>: Python interpreter stopped
2022-10-20 17:22:49.998 T:2646     INFO <general>: initializing python engine.
2022-10-20 17:22:52.480 T:2646    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'data'
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/plugin.video.TVOnline.ro/main.py", line 279, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/pi/.kodi/addons/plugin.video.TVOnline.ro/main.py", line 251, in router
                                                       voyo_functions.play_video(params['channel_endpoint'], common_vars.__AddonID__, common_vars.__voyo_CookieJar__, common_vars.__voyo_Session__, MyAddon_DataDir)
                                                     File "/home/pi/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/voyo/functions.py", line 240, in play_video
                                                       if _auth_['data']['is_subscribed']:
                                                   KeyError: 'data'
                                                   -->End of Python script error report<--
                                                   
2022-10-20 17:22:52.603 T:2646     INFO <general>: Python interpreter stopped
2022-10-20 17:22:52.616 T:2312    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.TVOnline.ro/?action=play&account=voyo.ro&channel_endpoint=https%3A%2F%2Fmedia.cms.protv.ro%2Fembed%2Fvoyo-pro-tv-live]
```

**Comment by dimovnike** [comment]
mai jos e logul cu debug:

```
2022-10-20 17:29:33.179 T:2740     INFO <general>: CPythonInvoker(25, /home/pi/.kodi/addons/plugin.video.TVOnline.ro/main.py): script successfully run                                                                                 
2022-10-20 17:29:33.341 T:2740     INFO <general>: Python interpreter stopped                                                                                                                                                          
2022-10-20 17:29:34.640 T:2746     INFO <general>: initializing python engine.                                                                                                                                                         
2022-10-20 17:29:36.606 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:Enter function                                                                                                                               
                                                                                                                                                                                                                                       
2022-10-20 17:29:36.606 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:[ Addon settings ] digionline_Enabled = false                                                                                                
                                                                                                                                                                                                                                       
2022-10-20 17:29:36.606 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:[ Addon settings ] digionline_DeviceManufacturer = __DEFAULT_DEVICE_MAUFACTURER__
                                                                                                                   
2022-10-20 17:29:36.606 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:[ Addon settings ] digionline_DeviceModel = __DEFAULT_DEVICE_MODEL__
                                                                                                                   
2022-10-20 17:29:36.606 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:[ Addon settings ] digionline_AndroidVersion = __DEFAULT_ANDROID_VERSION__
                                                                                                                   
2022-10-20 17:29:36.606 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:[ Addon settings ] voyo_Enabled = true
                                                                                                                   
2022-10-20 17:29:36.607 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:[ Addon settings ] ShowTitleInChannelList = false
                                                   
2022-10-20 17:29:36.607 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:[ Addon settings ] DebugEnabled = true
                                                    
2022-10-20 17:29:36.607 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:[ Addon settings ] PVRIPTVSimpleClientIntegration_m3u_FileRefreshTime = 00:05
                                                    
2022-10-20 17:29:36.607 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:[ Addon settings ] PVRIPTVSimpleClientIntegration_EPG_FileRefreshTime = 00:10
                                                    
2022-10-20 17:29:36.607 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:Enter function
                                                    
2022-10-20 17:29:36.608 T:2746    ERROR <general>: DEBUG:service.plugin.video.TVOnline.ro:'voyo.ro'  ==> Enabled
                                                    
2022-10-20 17:29:36.629 T:2746    ERROR <general>: DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): crm.cms.protv.ro:443
                                                    
2022-10-20 17:29:36.753 T:2746    ERROR <general>: DEBUG:urllib3.connectionpool:https://crm.cms.protv.ro:443 "GET /api/v1/users/login-check HTTP/1.1" 401 None
                                                    
2022-10-20 17:29:36.763 T:2746    ERROR <general>: DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): voyo.protv.ro:443
                                                    
2022-10-20 17:29:37.047 T:2746    ERROR <general>: DEBUG:urllib3.connectionpool:https://voyo.protv.ro:443 "POST /login HTTP/1.1" 303 None
                                                    
2022-10-20 17:29:37.155 T:2746    ERROR <general>: DEBUG:urllib3.connectionpool:https://crm.cms.protv.ro:443 "GET /api/v1/users/login-check HTTP/1.1" 401 None
                                                    
2022-10-20 17:29:37.162 T:2746    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'data'
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/plugin.video.TVOnline.ro/main.py", line 279, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/pi/.kodi/addons/plugin.video.TVOnline.ro/main.py", line 251, in router
                                                       voyo_functions.play_video(params['channel_endpoint'], common_vars.__AddonID__, common_vars.__voyo_CookieJar__, common_vars.__voyo_Session__, MyAddon_DataDir)
                                                     File "/home/pi/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/voyo/functions.py", line 240, in play_video
                                                       if _auth_['data']['is_subscribed']:
                                                   KeyError: 'data'
                                                   -->End of Python script error report<--
                                                    
2022-10-20 17:29:37.277 T:2746     INFO <general>: Python interpreter stopped
2022-10-20 17:29:37.309 T:2312    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.TVOnline.ro/?action=play&account=voyo.ro&channel_endpoint=https%3A%2F%2Fmedia.cms.protv.ro%2Fembed%2Fvoyo-
pro-tv-live]

```

**Comment by cralin** [comment]
Te rog sa activezi "Debug loging" in setarile addon-ului si dupa ce replici problema te rog sa-mi trimiti toate log-urile generate de addon.

**Comment by cralin** [comment]
Inchis din lipsa de input
