### ISSUE TITLE
TV app

### ISSUE THREAD

**Issue by freegigi** [cralin/plugin.video.TVOnline.ro#26]
Salut,

Daca selectez 'Behave as TV app' primesc erorare. asta gasesc in kodi.log:

2023-12-01 16:46:59.815 T:3563    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'category_name'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/main.py", line 380, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/main.py", line 274, in router
                                                       digionline_functions.digionline__listCategories(params['behaveas'], common_vars.__AddonID__, common_vars.__digion
line_Session__, MyAddon_DataDir)
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/digionline/functions.py", line 1051, in digionli
ne__listCategories
                                                       common_vars.__logger__.debug('Category:  id = \'' + str(category_data['id_category']) + '\', Name = \'' + str(cat
egory_data['category_name']) + '\', Title = \'' + str(category_data['category_desc']) + '\'')
                                                                                                                                                                     ~~~
~~~~~~~~~~^^^^^^^^^^^^^^^^^
                                                   KeyError: 'category_name'
                                                   -->End of Python script error report<--
                                                   
2023-12-01 16:46:59.942 T:3562    error <general>: GetDirectory - Error getting plugin://plugin.video.TVOnline.ro/?account=digionline.ro&action=list_categories&behaveas
=TV
2023-12-01 16:46:59.972 T:836     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.TVOnline.ro/?account=digionline.ro&action=list_categories&behavea
s=TV) failed
2023-12-01 16:47:00.573 T:3565  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. 
Please use the respective setter in InfoTagVideo.
2023-12-01 16:47:05.266 T:882      info <general>: Skipped 1 duplicate messages..
2023-12-01 16:47:05.266 T:882     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'category_name'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 462, in <module>
                                                       schedule.run_pending()
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/schedule/__init__.py", line 780, in run_pending
                                                       default_scheduler.run_pending()
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/schedule/__init__.py", line 100, in run_pending
                                                       self._run_job(job)
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/schedule/__init__.py", line 172, in _run_job
                                                       ret = job.run()
                                                             ^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/schedule/__init__.py", line 661, in run
                                                       ret = self.job_func()
                                                             ^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 140, in schedule_jobs
                                                       PVRIPTVSimpleClientIntegration_init_m3u_file()
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 247, in PVRIPTVSimpleClientIntegration_init_
m3u_file
                                                       PVRIPTVSimpleClientIntegration_update_m3u_file()
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 283, in PVRIPTVSimpleClientIntegration_updat
e_m3u_file
                                                       _current_channel_number_ = digionline_functions.digionline__tv_updateM3Ufile(_tmp_m3u_file_, _current_channel_num
ber_, common_vars.__ServiceID__, common_vars.__digionline_ServiceSession__, MyServiceAddon_DataDir)
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/digionline/functions.py", line 1480, in digionli
ne__tv_updateM3Ufile
                                                       common_vars.__logger__.debug('Category:  id = \'' + str(_category_['id_category']) + '\', Name = \'' + str(_categ
ory_['category_name']) + '\', Title = \'' + str(_category_['category_desc']) + '\'')
                                                                                                                                                                  ~~~~~~
~~~~^^^^^^^^^^^^^^^^^
                                                   KeyError: 'category_name'
                                                   -->End of Python script error report<--

Inainte a mers. Canpurile sunt completate corect.

Multumesc,

**Comment by cralin** [comment]
Salut,

Activeaza "debig logging" in configuratia addon-ului si dupa ce ai replicat problema, te rog sa-mi trimiti toate fisierele log generate de add-on

**Comment by cralin** [comment]
Problema este rezolvata in versiunea 20.0.10
