### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by dumol** [cralin/plugin.video.TVOnline.ro#30]
Kodi 21.1-Omega. Log:

```
2024-09-25 19:39:10.091 T:595     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   Traceback (most recent call last):
                                                     File "/home/dumol/.var/app/tv.kodi.Kodi/data/addons/plugin.video.TVOnline.ro/main.py", line 283, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/dumol/.var/app/tv.kodi.Kodi/data/addons/plugin.video.TVOnline.ro/main.py", line 245, in router
                                                       digionline_functions.digionline__playVideo(params['behaveas'], params['channel_id'], common_vars.__AddonID__, common_vars.__digionline_Session__, MyAddon_DataDir)
                                                     File "/home/dumol/.var/app/tv.kodi.Kodi/data/addons/plugin.video.TVOnline.ro/resources/lib/digionline/functions.py", line 1306, in digionline__playVideo
                                                       if is_helper.check_inputstream():
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/dumol/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 420, in check_inputstream
                                                       if self.drm == 'widevine' and not self._supports_widevine():
                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/dumol/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 163, in _supports_widevine
                                                       if parse_version(config.WIDEVINE_MINIMUM_KODI_VERSION[system_os()]) > parse_version(kodi_version()):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   -->End of Python script error report<--

2024-09-25 19:39:10.130 T:7       error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.TVOnline.ro/?account=digionline.ro&behaveas=Phone&action=play&channel_id=90]
```

**Comment by cralin** [comment]
@dumol ,
pe RPI4 al meu cu LibreELEC nu reusesc sa replic eroarea care o vezi tu la tine.

Ai in continuare respectiva eroare sau ai rezolvat ?
Daca ai rezolvat, cum ai rezolvat ?

**Comment by dumol** [comment]
S-a rezolvat într-adevăr, nu mai am nici io probleme. Probabil printr-un update de add-on, pentru că la mine se fac automat.

Mulțam pentru atenționare, în ultima vreme nici nu mai verificasem de merge ori ba, mă resemnasem că s-a bușit…

**Comment by cralin** [comment]
Aici zice ca e rezolvat in inputstreamhelper 0.7.0:  [https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/570#issuecomment-2376262356](https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/570#issuecomment-2376262356)

**Comment by dumol** [comment]
La prima vedere, ăsta pare să fi fost fixu': https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/561. Și a fost prins în `inputstreamhelper` 0.7.0.

**Comment by cralin** [comment]
Am inchis Issue-ul asa fiindca oricum problema nu are atreaba cu acest addon si este deja rezolvata in inputstreamhelper 0.7.0
