### ISSUE TITLE
Broken protvplus.ro support

### ISSUE THREAD

**Issue by dumol** [cralin/plugin.video.TVOnline.ro#4]
ProTV+ channels have not work for me lately on both Linux and RPi installations. Didn't care much until I found out we play England on Wembley this Sunday and it's only available on ProTV. :D

Kodi logs for current plugin version, 19.2.1:

```
2021-06-04 19:14:38.014 T:30859    INFO <general>: CPythonInvoker(12, /home/dumol/.kodi/addons/plugin.video.TVOnline.ro/main.py): script successfully run
2021-06-04 19:14:38.072 T:30859    INFO <general>: Python interpreter stopped
2021-06-04 19:16:22.344 T:30917    INFO <general>: initializing python engine.
2021-06-04 19:16:24.047 T:30917   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/main.py", line 288, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/main.py", line 260, in router
                                                       protvplus_functions.play_video(params['channel_endpoint'], common_vars.__AddonID__, common_vars.__protvplus_CookieJar__, common_vars.__protvplus_Session__, MyAddon_DataDir)
                                                     File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/protvplus/functions.py", line 303, in play_video
                                                       _raw_stream_data_ = re.findall('\'player-1\', (.+?), {"video"', _request_.content.decode(), re.IGNORECASE|re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2021-06-04 19:16:24.112 T:30917    INFO <general>: Python interpreter stopped
2021-06-04 19:16:24.126 T:30653   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.TVOnline.ro/?action=play&account=protvplus.ro&channel_endpoint=https%3A%2F%2Fprotvplus.ro%2Fapi%2Fv1%2Fuser%2Flive%3Fv%3Dfd2967d3-7c3a-49df-89e0-713c63b68ec4%26amp%3Bch%3D1]
2021-06-04 19:16:24.143 T:30653    INFO <general>: CVideoPlayer::CloseFile()
2021-06-04 19:16:24.148 T:30653    INFO <general>: VideoPlayer: waiting for threads to exit
2021-06-04 19:16:24.152 T:30786    INFO <general>: CVideoPlayer::OnExit()
2021-06-04 19:16:24.152 T:30786    INFO <general>: Closing stream player 1
```

**Comment by cralin** [comment]
Please use the version 19.2.2

**Comment by dumol** [comment]
Confirmed. That was really quick… Thanks!

**Comment by cralin** [comment]
Actually the fix was already there 3 hours before the Issue was reported   :)

> 19.2.2  cralin released this 6 hours ago

> dumol opened this issue 3 hours ago
